REM INSERTING into SIAR_FERIADO
SET DEFINE OFF;
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('1','Imaculada Conçeição','08-12-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('2','Natal','25-12-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('3','Assunção Nossa Senhora','15-08-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('4','Dia de Portugal','10-06-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('5','Dia do Trabalhador','01-05-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('7','Dia da Liberdade','25-04-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('8','Pascóa','31-03-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('9','Sexta Feira Santa','18-06-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('10','Dia de Ano Novo','01-12-2024');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('11','Feraido Bonito','12-07-2033');
Insert into SIAR_FERIADO (COD_FERIADO,DESC_FERIADO,DTA_FERIADO) values ('21','Feriado do Fim do Mês','31-05-2024');
